# Generated by Django 2.2.4 on 2019-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=60)),
                ('creditos', models.IntegerField()),
            ],
        ),
    ]
